### ISSUE TITLE
Error in stringr::str_match

### ISSUE THREAD

**Issue by privefl** [RMHogervorst/badgecreatr#19]
Hello, 

I just installed your package and tested it with:
`badgecreatr::badgeplacer(status = "wip", githubaccount = "privefl", githubrepo = "mypack")`.
Yes, I was not inspired with the name, I should change it in the near future.
I got the following error:
`Error in stringr::str_match(grep("R \\(", description, value = TRUE),  : 
  subscript out of bounds`.

Note that I already have a README.Rmd with some badges in it (got them from `devtools`):
[README.zip](https://github.com/RMHogervorst/badgecreatr/files/355856/README.zip)

Thanks for this package anyway.
Florian

**Comment by RMHogervorst** [comment]
Hi florian, there is an error in your description file, did you use devtools? You don't declare which version of r you are using in "Depends: "

That's why  the search function can't find the r version. 

Perhaps the error message should be more informative...

Or perhaps a unit test. 
 Thanks for the issue!

**Comment by privefl** [comment]
Ok, thanks.
